version: '2'
services:
  ##
  # Nginx Reverse Proxy
  ##
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/corncandy/Workspace/ssl:/etc/nginx/certs
    environment:
      - DEFAULT_HOST=www.muyunsong.com
  ##
  # Jekyll based blog
  ##
  jekyll-blog:
    image: jekyll/jekyll
    container_name: jekyll-blog
    ports:
      - 4000
    volumes:
      - /home/corncandy/Workspace/corncandy.github.io:/srv/jekyll
    environment:
      - VIRTUAL_HOST=www.muyunsong.com
      - VIRTUAL_PORT=4000
  ##
  # Jenkins CI
  ##
  data-jenkins:
    image: busybox
    container_name: data-jenkins
    volumes:
      - /var/jenkins_home
  jenkins-ci:
    image: jenkins:alpine
    container_name: jenkins-ci
    ports:
      - 8080
      - 50000
    user: root
    volumes:
      - /etc/timezone:/etc/timezone
      - /home/corncandy/Workspace/corncandy.github.io:/srv/jekyll
      - /home/corncandy/Workspace/gitbooks/wd-frontend:/srv/gitbook
      - /home/corncandy/Workspace/jenkins_home:/var/jenkins_home
    environment:
      - VIRTUAL_HOST=ci.muyunsong.com
      - VIRTUAL_PORT=8080
  ##
  # GitBook based WUI framework
  ##
  gitbook-wui:
    image: fellah/gitbook
    container_name: gitbook-wui
    ports:
      - 4000
      - 35729
    volumes:
      - /home/corncandy/Workspace/gitbooks/wd-frontend:/srv/gitbook
    environment:
      - VIRTUAL_HOST=wui.muyunsong.com
      - VIRTUAL_PORT=4000
  ##
  # Static site of slideshow
  ##
  nginx-slideshow:
    image: nginx
    container_name: nginx-slideshow
    ports:
      - 80
    volumes:
      - /home/corncandy/Workspace/slideshows:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=slideshow.muyunsong.com
  ##
  # Redis
  ##
#  redis:
#    image: redis
#    container_name: redis
#    ports: 
#      - 6379
  ##
  # MongoDB
  ##
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017
    volumes:
      - /home/corncandy/Workspace/mongodb:/data/db
  mongo-admin:
    image: mongo-express
    container_name: mongo-admin
    links:
      - mongo:mongo
    ports:
      - 8081
    environment:
      - VIRTUAL_HOST=db.muyunsong.com
      - VIRTUAL_PORT=27017
  ##
  # Node Test
  ##
#  node-test:
#    build: node-test
#    container_name: node-test
#    ports:
#      - 3000
#    volumes:
#      - /home/corncandy/Workspace/node-test:/usr/src/app
#    links:
#      - redis:redis
#      - mongo:mongodb
  
